FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

#RUN rasa train

EXPOSE 8080

CMD ["sh", "-c", "rasa run --enable-api --cors '*' --port ${PORT:-8080}"]