FROM rasa/rasa:3.6.21

WORKDIR /app

COPY . /app

EXPOSE 8080

#CMD ["run", "--enable-api", "--cors", "*", "--port", "8080"] 
CMD ["run","--model","/app/models/20260705-003214-teal-audio.tar.gz","--enable-api","--cors","*","--port","8080"]